apiVersion: v1
kind: PersistentVolume
metadata:
    name: autocache-twitter
    labels:
        app: autocache-twitter
        volume: autocache-twitter
spec:
    capacity:
        storage: 1Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/autocache-twitter