apiVersion: v1
kind: PersistentVolume
metadata:
    name: confluence-postgresql
    labels:
        app: confluence
        volume: confluence-postgresql
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /volumes/confluence-postgresql