apiVersion: v1
kind: PersistentVolume
metadata:
    name: confluence-home
    labels:
        app: confluence
        volume: confluence-confluence-home
spec:
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /volumes/confluence-home