apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-etc
    labels:
        app: gitlab
        volume: gitlab-gitlab-ce-etc
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /volumes/gitlab-etc