apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-postgresql
    labels:
        app: gitlab
        volume: gitlab-postgresql
spec:
    capacity:
        storage: 4Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/gitlab-postgresql