apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-data
    labels:
        app: gitlab
        volume: gitlab-gitlab-ce-data
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /volumes/gitlab-data