apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins
    labels:
        app: jenkins
spec:
    capacity:
        storage: 8Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/jenkins-master