apiVersion: v1
kind: PersistentVolume
metadata:
    name: lb-acme
spec:
    capacity:
        storage: 1Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/lb-acme