apiVersion: v1
kind: PersistentVolume
metadata:
    name: traefik-acme
    labels:
        app: traefik
spec:
    capacity:
        storage: 1Mi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/lb-acme